version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: sudo npm install -g npm@latest
      - run: npm install cypress
      - run: npm install cypress-mochawesome-reporter
      - run: npm install cypress-testrail-reporter
      - run: npm install axios
      - run: npm install request
      - run: npm run test
workflows:
  test_my_app:
    jobs:
      - test